package cmd

import (
	"bytes"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// docsHeader is the hand-written section docs/cli.md opens with, ahead of
// the generated command reference GenerateDocs appends below it.
const docsHeader = `# freshbooks CLI reference

A kubectl-style command-line client for the FreshBooks REST API. This
file's "Command reference" section below is generated by ` + "`mise run docs`" + `
(` + "`scripts/docs.sh`" + `, which runs ` + "`freshbooks docs`" + `) from the cobra command
tree; do not hand-edit past that point.

## Install

Download a release archive from the ` + "`cli/vX.Y.Z`" + ` GitHub releases, or build
from source: ` + "`go build ./cli/cmd/freshbooks`" + ` from the repository root
(requires the ` + "`go.work`" + ` workspace, so build from inside the repo).

## First login

1. Register an app at https://www.freshbooks.com/api/start and note its
   client id and secret. Its registered redirect URI must be
   ` + "`https://localhost:8765/callback`" + ` (or whatever ` + "`--callback-port`" + ` you pass).
2. Run ` + "`freshbooks auth login --client-id <id> --client-secret <secret>`" + `.
   This opens a browser to FreshBooks' consent screen and starts a
   loopback HTTPS listener on 127.0.0.1 to receive the redirect.
3. Your browser will warn that the certificate is untrusted -- this is
   expected. The CLI generates a throwaway, self-signed certificate for
   this one callback, in-process, and never writes it to disk. Accept the
   warning to continue.
4. On success the CLI stores the token under
   ` + "`$XDG_CONFIG_HOME/freshbooks/credentials/<context>.json`" + ` (0600), and prints
   nothing from the token itself.
5. Over SSH or in an environment with no browser, pass ` + "`--no-browser`" + `: the
   CLI prints the authorization URL and reads either the full redirected
   URL or a bare authorization code from stdin instead of listening.

## Contexts

A context is a named account/business/business-uuid triple plus its own
credentials file. ` + "`freshbooks config set-context <name> --account ... --business ...`" + `
creates or updates one; ` + "`freshbooks config use-context <name>`" + ` switches
` + "`config.yaml`" + `'s current context; ` + "`freshbooks config contexts`" + ` lists them;
` + "`freshbooks config view`" + ` prints the resolved file. ` + "`config.yaml`" + ` never carries
a secret -- credentials are a separate file per context, managed by
` + "`freshbooks auth`" + `.

Every scope field and every global flag resolves in this order: an
explicit flag, then an environment variable, then the current context's
config.yaml value, then a built-in default. An empty environment variable
counts as unset, not as an explicit empty value.

## Output formats

` + "`-o/--output`" + ` selects ` + "`json`" + `, ` + "`yaml`" + `, ` + "`table`" + `, or ` + "`name`" + `. The default is ` + "`table`" + `
when stdout is a terminal and ` + "`json`" + ` otherwise, so scripts and pipelines get
structured output without passing the flag explicitly. ` + "`--no-headers`" + `
suppresses the header row in table output; ` + "`-q/--quiet`" + ` suppresses
non-result chatter (never errors).

## Exit codes

| Code | Meaning |
|---|---|
| 0 | success |
| 1 | an API or other runtime error |
| 2 | a usage error: a bad flag, a malformed --file body, a missing scope, or --all combined with --page/--per-page |
| 3 | an auth error: no stored credentials for the context, or the API answered 401 |
| 4 | the API answered 404 |

Under ` + "`-o json`" + `, an error is one JSON object on stderr:
` + "`{\"error\": {\"status\", \"code\", \"message\", \"field\", \"family\", \"exit\"}}`" + `.
Otherwise it is one human-readable line on stderr.

## Automation notes

Every registry command accepts ` + "`--dry-run`" + `, which prints the request's
method and URL (and its body, for a write) to stdout and sends nothing --
useful for verifying a command's shape before running it for real.
Destructive commands (the D-annotated ones in the command reference below)
refuse to run without ` + "`--yes`" + ` when stdin is a terminal.

## The api escape hatch

` + "`freshbooks api <METHOD> <path> [-f file|-] [--query key=value]...`" + ` calls the same
authenticated, retrying transport every registry command uses, for an
endpoint this CLI does not model as its own command yet. path is rooted at
the API base, e.g. ` + "`/accounting/account/ACM123/systems/systems/1`" + `.

## Security notes

- The access token is printed by exactly one command: ` + "`freshbooks auth token`" + `.
  Every other command, including ` + "`--dry-run`" + `, ` + "`config view`" + `, and
  ` + "`auth status`" + `, never prints it.
- Credentials files are written 0600 inside a 0700 directory.
- The loopback login listener's TLS certificate is generated fresh for
  each login, in-process, and never touches disk.

## Command reference

`

// linkHandler converts a cobra/doc cross-reference filename
// (e.g. "freshbooks_clients_list.md") into an in-page anchor
// ("#freshbooks-clients-list") matching the heading GenMarkdownCustom
// writes ("## freshbooks clients list") once a standard Markdown renderer
// slugifies it (lowercase, spaces to hyphens).
func linkHandler(name string) string {
	name = strings.TrimSuffix(name, ".md")
	name = strings.ReplaceAll(name, "_", "-")
	return "#" + name
}

// GenerateDocs renders the full docs/cli.md content: docsHeader followed
// by one cobra/doc Markdown section per command in the tree, depth-first,
// children sorted by name at each level for a deterministic, idempotent
// result (mise run docs must produce byte-identical output on every run
// against an unchanged command tree).
func GenerateDocs(root *cobra.Command) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(docsHeader)
	if err := renderDocsTree(&buf, root); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func renderDocsTree(buf *bytes.Buffer, c *cobra.Command) error {
	// DisableAutoGenTag suppresses cobra/doc's "Auto generated ... on
	// <today's date>" footer, which would otherwise make every run
	// non-idempotent.
	c.DisableAutoGenTag = true
	c.InitDefaultHelpCmd()
	c.InitDefaultHelpFlag()
	if err := doc.GenMarkdownCustom(c, buf, linkHandler); err != nil {
		return err
	}

	children := make([]*cobra.Command, 0, len(c.Commands()))
	for _, child := range c.Commands() {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
			continue
		}
		children = append(children, child)
	}
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	for _, child := range children {
		if err := renderDocsTree(buf, child); err != nil {
			return err
		}
	}
	return nil
}
