package cmd

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateDocs(t *testing.T) {
	root := NewRootCmd("test")
	content, err := GenerateDocs(root)
	if err != nil {
		t.Fatalf("GenerateDocs() error = %v", err)
	}
	s := string(content)
	if !strings.Contains(s, "# freshbooks CLI reference") {
		t.Error("missing hand-written header")
	}
	if !strings.Contains(s, "## freshbooks clients list") {
		t.Error("missing a generated command section")
	}
	if !strings.Contains(s, "## freshbooks auth login") {
		t.Error("missing the auth login section")
	}
	if strings.Contains(s, "Auto generated by spf13/cobra") {
		t.Error("DisableAutoGenTag did not suppress the date-stamped footer (would break idempotency)")
	}
}

func TestGenerateDocsIsIdempotent(t *testing.T) {
	root1 := NewRootCmd("test")
	first, err := GenerateDocs(root1)
	if err != nil {
		t.Fatal(err)
	}
	root2 := NewRootCmd("test")
	second, err := GenerateDocs(root2)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Error("GenerateDocs is not idempotent across two fresh root commands")
	}
}

func TestLinkHandler(t *testing.T) {
	tests := []struct{ in, want string }{
		{"freshbooks_clients_list.md", "#freshbooks-clients-list"},
		{"freshbooks_auth_login.md", "#freshbooks-auth-login"},
	}
	for _, tt := range tests {
		if got := linkHandler(tt.in); got != tt.want {
			t.Errorf("linkHandler(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func TestDocsCommand(t *testing.T) {
	t.Run("[happy] writes the generated reference to the given file", func(t *testing.T) {
		out := filepath.Join(t.TempDir(), "cli.md")
		code := Run([]string{"docs", out}, discardStdin, io.Discard, io.Discard, "test")
		if code != 0 {
			t.Fatalf("exit = %d", code)
		}
		data, err := os.ReadFile(out)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), "# freshbooks CLI reference") {
			t.Error("generated file missing the header")
		}
	})

	t.Run("[sad] an unwritable path is a runtime error", func(t *testing.T) {
		code := Run([]string{"docs", "/nonexistent-dir-xyz/cli.md"}, discardStdin, io.Discard, io.Discard, "test")
		if code != 1 {
			t.Fatalf("exit = %d, want 1", code)
		}
	})

	t.Run("[edge] docs is hidden from the generated reference itself", func(t *testing.T) {
		root := NewRootCmd("test")
		content, err := GenerateDocs(root)
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(content), "## freshbooks docs") {
			t.Error("the hidden docs command should not appear in its own generated reference")
		}
	})
}
