package docsgen

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestLinkHandler(t *testing.T) {
	tests := []struct{ in, want string }{
		{"freshbooks_clients_list.md", "#freshbooks-clients-list"},
		{"freshbooks_auth_login.md", "#freshbooks-auth-login"},
	}
	for _, tt := range tests {
		if got := linkHandler(tt.in); got != tt.want {
			t.Errorf("linkHandler(%q) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

func testTree() *cobra.Command {
	root := &cobra.Command{Use: "freshbooks", Short: "test root"}
	clients := &cobra.Command{Use: "clients", Short: "manage clients"}
	root.AddCommand(clients)
	clients.AddCommand(&cobra.Command{
		Use: "list", Short: "list clients",
		Run: func(*cobra.Command, []string) {},
	})
	// hidden commands must not appear in the generated reference.
	root.AddCommand(&cobra.Command{
		Use: "docs <file>", Short: "hidden docs command", Hidden: true,
		Run: func(*cobra.Command, []string) {},
	})
	return root
}

func TestGenerate(t *testing.T) {
	content, err := Generate(testTree())
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	s := string(content)
	if !strings.Contains(s, "# freshbooks CLI reference") {
		t.Error("missing hand-written header")
	}
	if !strings.Contains(s, "## freshbooks clients list") {
		t.Error("missing a generated leaf command section")
	}
	if !strings.Contains(s, "## freshbooks clients") {
		t.Error("missing a generated parent command section")
	}
	if strings.Contains(s, "Auto generated by spf13/cobra") {
		t.Error("DisableAutoGenTag did not suppress the date-stamped footer (would break idempotency)")
	}
	if strings.Contains(s, "hidden docs command") {
		t.Error("a Hidden command must not appear in the generated reference")
	}
}

func TestGenerateIsIdempotent(t *testing.T) {
	first, err := Generate(testTree())
	if err != nil {
		t.Fatal(err)
	}
	second, err := Generate(testTree())
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Error("Generate is not idempotent across two fresh command trees")
	}
}
